## A basic GitHub Actions workflow for your Quarkus application.

name: CD build datastore

on:
  push:
    branches: [ main, dev ]
  workflow_dispatch:

env:
  DH_USERNAME: ${{secrets.DOCKER_HUB_LOGIN}}
  DH_TOKEN: ${{secrets.DOCKER_HUB_PWD}}
  IMAGE_NAME: 'data-store'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      
      - name: Setup Helm
        uses: azure/setup-helm@v3

      - name: Semantic Release
        uses: codfish/semantic-release-action@v3
        id: semantic
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branches: |
            [
              'release',
              { "name": "main", "prerelease": "dev" }
            ]
          plugins: |
            [
              [
                "@semantic-release/commit-analyzer",
                { "preset": "angular", "releaseRules": [ { "type": "refactor", "release": "patch" } ] }
              ],
              "@semantic-release/release-notes-generator",
              "@semantic-release/github"
            ]

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: maven

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_LOGIN }}
          password: ${{ secrets.DOCKER_HUB_PWD }}
        
      - name: Build and tag Docker image
        if: steps.semantic.outputs.new-release-published == 'true'
        run: |
          ./mvnw package -B \
            -Dquarkus.container-image.tag=v${RELEASE_VERSION} \
            -Dquarkus.container-image.name=${IMAGE_NAME} \
            -Dquarkus.container-image.push=true
          docker image ls

      - name: Log in to Docker Hub Helm Registry
        if: steps.semantic.outputs.new-release-published == 'true'
        run: |
          echo "$DH_TOKEN" | helm registry login -u "$DH_USERNAME" --password-stdin docker.io

      - name: Push Helm chart to Docker Hub OCI repo
        if: steps.semantic.outputs.new-release-published == 'true'
        run: |
          sed -i "s/^version:.*/version: v$RELEASE_VERSION/" ./charts/Chart.yaml
          CHART_NAME=$(grep '^name:' ./charts/Chart.yaml | awk '{print $2}')
          helm dependency update ./charts
          helm package ./charts -d ./charts
          helm push ./charts/$CHART_NAME-v$RELEASE_VERSION.tgz oci://docker.io/$DH_USERNAME