name: Stable release
on:
  push:
    tags:
      - "*"

env:
  QUARKUS_CONTAINER_IMAGE_USERNAME: ${{ secrets.DOCKER_HUB_LOGIN }}
  QUARKUS_CONTAINER_IMAGE_PASSWORD: ${{ secrets.DOCKER_HUB_PWD }}
  IMAGE_NAME: 'data-store'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout gh-repo
        uses: actions/checkout@v3
      
      - name: Setup Helm
        uses: azure/setup-helm@v3

      - id: get_version
        uses: battila7/get-version-action@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: maven
        
      - name: Build
        if: steps.get_version.outputs.is-semver == 'true'
        run: |
          ./mvnw package -B \
            -Dquarkus.container-image.tag=${{steps.get_version.outputs.version}} \
            -Dquarkus.container-image.name=${IMAGE_NAME} \
            -Dquarkus.container-image.push=true

      - name: Log in to Docker Hub Helm Registry
        if: steps.get_version.outputs.is-semver == 'true'
        run: |
          echo "$DH_TOKEN" | helm registry login -u "$DH_USERNAME" --password-stdin docker.io

      - name: Push Helm chart to Docker Hub OCI repo
        if: steps.get_version.outputs.is-semver == 'true'
        run: |
          sed -i "s/^version:.*/version: ${{steps.get_version.outputs.version}}/" ./charts/Chart.yaml
          CHART_NAME=$(grep '^name:' ./charts/Chart.yaml | awk '{print $2}')
          helm dependency update ./charts
          helm package ./charts -d ./charts
          helm push ./charts/$CHART_NAME-${{steps.get_version.outputs.version}}.tgz oci://docker.io/$DH_USERNAME